#import "common.typ": *

== Dependent type theory

We implement a dependent type theory in the tradition of Martin-Löf. We assume familiarity with the simply typed lambda calculus and focus on what distinguishes our system.

=== Syntax

The core theory maintains a syntactic distinction between _types_ and _terms_ (Tarski-style universes). The grammar is:

$
  ell &::= n | 0 | sans("succ")(ell) | max(ell, ell) & quad "(universe levels)" \
  A, B &::= sans("Type")_ell | Pi (x : A). B | sans("El")(t) & quad "(types)" \
  t, s &::= sans("Type'")_ell | x_i | c.{overline(ell)} | lambda (x : A). t | t thin s | Pi' (x : t). s | t.k | sans("let") thin x : A := t; thin s & quad "(terms)"
$

Universe levels $ell$ form an algebra of named variables $n$, zero, successor, and binary maximum. Types include universes $sans("Type")_ell$, dependent function types $Pi (x : A). B$, and the decoding operation $sans("El")(t)$ converting a term-level code into a type. The term formers $sans("Type'")_ell$ and $Pi' (x : t). s$ are codes for the corresponding type formers. Variables $x_i$ are de Bruijn indices, $c.{overline(ell)}$ are global constants applied to universe level arguments, and $t.k$ projects the $k$-th field.

For example, the type `Nat -> Nat` is $Pi (x : sans("El")(sans("Nat"))). sans("El")(sans("Nat"))$, where $sans("Nat")$ is a term-level constant of type $sans("Type")_0$. $sans("El")$ decodes the term $sans("Nat")$ into the type it represents. Without it, $sans("Nat")$ cannot appear where a type is expected --- the syntactic categories are disjoint.

In Russell-style theories (as in Lean 4), types and terms share a single syntactic sort: `Nat` can appear directly as a type without coercion. In our Tarski-style formulation, every position in the syntax tree is unambiguously either a type or a term. We prefer Tarski style because the syntactic separation simplifies the metatheory of our system.

=== Judgement forms

The theory has six judgement forms, parameterised by a global environment $Delta$ and a local context $Gamma$:

$
  & tack.r Delta thin sans("sig")                   & quad & "global environment well-formedness" \
  & Delta; Gamma tack.r                             & quad & "context well-formedness" \
  & Delta; Gamma tack.r A thin sans("type")         & quad & "type well-formedness" \
  & Delta; Gamma tack.r t : A                       & quad & "term typing" \
  & Delta; Gamma tack.r A equiv B thin sans("type") & quad & "judgemental type equality" \
  & Delta; Gamma tack.r a equiv b : A               & quad & "judgemental term equality"
$

$Delta$ maps constant names to their definitions and types. $Gamma$ is a telescope of typed bindings.

=== Typing rules

Type formation follows the grammar: $sans("Type")_ell$ is well-formed in any well-formed context, $sans("El")(t)$ when $t$ has type $sans("Type")_ell$, and $Pi (x : A). B$ when $A$ and $B$ are.

The two central typing rules are introduction and elimination of dependent functions:

#align(center, stack(
  dir: ltr,
  spacing: 2em,
  prooftree(rule(
    name: $Pi sans("-I")$,
    $Delta; Gamma tack.r lambda (x : A). b : Pi (x : A). B$,
    $Delta; Gamma tack.r A thin sans("type")$,
    $Delta; Gamma, x : A tack.r b : B$,
  )),
  prooftree(rule(
    name: $Pi sans("-E")$,
    $Delta; Gamma tack.r f thin a : B[a\/x]$,
    $Delta; Gamma tack.r f : Pi (x : A). B$,
    $Delta; Gamma tack.r a : A$,
  )),
))

Lambdas introduce $Pi$ types; application eliminates them, substituting the argument into the codomain. The remaining rules are standard: variables by context lookup, constants by environment lookup, let-bindings by checking the bound value and then the body, and the conversion rule allowing a term of type $A$ to be given type $B$ when $A$ and $B$ are definitionally equal.

=== Definitional equality

Definitional equality is the least congruence generated by:

- $beta$-reduction: $quad (lambda (x : A). b) thin a equiv b[a\/x]$
- $delta$-reduction: $quad c.{overline(ell)} equiv t quad$ when $Delta(c) = t$
- $zeta$-reduction: $quad sans("let") thin x : A := a thin sans("in") thin b equiv b[a\/x]$
- $eta$-conversion: $quad f equiv lambda (x : A). f thin x quad$ at function type
- $iota$-reduction: recursor applied to a constructor computes to the corresponding branch

The full relation includes congruence, symmetry, transitivity, and closure under conversion for types.

=== Universe polymorphism

Universes are non-cumulative: $sans("Type")_ell$ does not belong to $sans("Type")_(ell')$ for $ell' > ell$. Definitions may be parameterised by universe level variables:

```lean
def id.{u} (α : Type u) (x : α) : α := x
```

At each use site, levels are instantiated explicitly: `id.{0}` or `id.{v}`. There is no universe level inference.

=== Inductive types

The theory supports user-defined inductive families. An inductive declaration introduces a type, its constructors, and a _recursor_. We illustrate with `Vector`:

```lean
inductive Vector.{u} (α : Type u) : Nat → Type u where
  | nil : Vector α Nat.zero
  | cons (n : Nat) (head : α) (tail : Vector α n) : Vector α (Nat.succ n)
```

It generates:
- The type `Vector.{u} : (α : Type u) → Nat → Type u`
- Constructors `Vector.nil.{u} : (α : Type u) → Vector α Nat.zero` and `Vector.cons.{u} : (α : Type u) → (n : Nat) → α → Vector α n → Vector α (Nat.succ n)`
- A recursor `Vector.rec.{v, u}` that eliminates a `Vector` by providing a case for `nil` and a case for `cons`:

```lean
Vector.rec.{v, u} :
  (α : Type u) →
  (C : (n : Nat) → Vector α n → Type v) →
  C Nat.zero (Vector.nil α) →
  ((n : Nat) → (head : α) → (tail : Vector α n) → C n tail → C (Nat.succ n) (Vector.cons α n head tail)) →
  (n : Nat) → (xs : Vector α n) → C n xs
```

All computation on inductives proceeds through the recursor; there is no primitive pattern matching. The computational rule (_iota-reduction_) fires when the recursor is applied to a constructor --- applying `Vector.rec` to `Vector.cons` reduces to the `cons` branch with the fields and recursive result as arguments.

As an example, `Vector.map` applies a function to each element:

```lean
def Vector.map.{u, v} (α : Type u) (β : Type v) (n : Nat) (f : α → β)
    : Vector.{u} α n → Vector.{v} β n :=
  Vector.rec.{v, u} α (fun k _ => Vector.{v} β k)
    (Vector.nil.{v} β)
    (fun m h _ => Vector.cons.{v} β m (f h))
    n
```

Structures (single-constructor inductives) support _projections_ $t.k$, extracting the $k$-th field from a constructor application.
