== Dependent type theory

In the simply typed lambda calculus, types and terms live in disjoint worlds: a type like `List Nat` cannot mention the value `3`.

A _dependent_ type theory @martinlof1984 lifts this separation. Types may mention terms. A vector indexed by its length has type `Vector Nat n` where `n : Nat` is a value-level natural; the type of a safe head function on non-empty vectors,

$ sans("head") : (n : sans("Nat")) -> sans("Vector") thin sans("Nat") thin (sans("succ") thin n) -> sans("Nat"), $

cannot be written without `n` appearing in the type. The Pi binder $Pi (x : A). B$ generalises the function arrow: $B$ is a type _depending on_ the value $x : A$, and ordinary $A -> B$ is the special case where $B$ is constant.

Once types contain terms, deciding whether two types are equal can require evaluating those terms. `Vector Nat (2 + 3)` and `Vector Nat 5` are the same type, but only after `2 + 3` reduces to `5`. Type checking therefore relies on _definitional equality_: a congruence relation under which two terms are interchangeable. The elaborator's _conversion checker_ decides this relation.

=== Reduction rules

Definitional equality is generated by five computation rules, named by the Greek letters traditional in the literature:

- *$beta$* (function application): $(lambda x. b) thin a equiv b[a slash x]$. The body $b$ with $a$ substituted for the bound variable.
- *$delta$* (definition unfolding): $c equiv t$ when the global environment binds the constant $c$ to body $t$.
- *$zeta$* (let inlining): $sans("let") thin x := a thin sans("in") thin b equiv b[a slash x]$.
- *$eta$* (definitional $eta$ at function type): $f equiv lambda x. f thin x$ at function type, regardless of whether $f$ is syntactically a lambda. Structures (single-constructor inductives) carry their own $eta$ rule: a term $s$ of a structure type is definitionally equal to the constructor applied to its projections, $c(s.1, dots, s.k) equiv s$.
- *$iota$* (recursor computation): a recursor applied to a constructor reduces to the corresponding branch. For `Nat`, $sans("Nat.rec") thin C thin z thin s thin (sans("succ") thin n) ~> s thin n thin (sans("Nat.rec") thin C thin z thin s thin n)$.

$delta$ is the rule that crosses definition boundaries; the other four operate on a term's own structure. The incremental architecture (@sec:incremental) tracks $delta$-dependencies precisely.

=== Universes

To avoid Girard's paradox, the system stratifies types into a predicative hierarchy:

$ sans("Type")_0 thin : thin sans("Type")_1 thin : thin sans("Type")_2 thin : thin dots $

Our universes are _non-cumulative_: $sans("Type")_u$ does not belong to $sans("Type")_v$ for $v > u$, only to $sans("Type")_(u+1)$. A definition can quantify over universe levels:

```lean
def id.{u} (α : Type u) (x : α) : α := x
```

Levels are written `.{u}`, treated as a separate sort of variable from term-level binders, and instantiated explicitly at each use site: `id.{0}` to get the identity at $sans("Type")_0$, `id.{u + 1}` to lift it. There is no universe-level inference; the programmer writes every level argument.

=== Tarski versus Russell

We use Tarski-style universes: types and terms inhabit disjoint syntactic sorts, with coercions $sans("Type'")_ell$ and $sans("El")$ between them @dybjer1996internal. Russell-style theories (Lean 4) merge the sorts.

=== Inductive types and recursors

An inductive type is introduced by its constructors. `Nat` is built from `Nat.zero` and `Nat.succ`. Computation on an inductive proceeds not through pattern matching but through a _recursor_ generated automatically alongside the type. The recursor takes a motive $C : sans("Nat") -> sans("Type")_u$ and one branch per constructor:

```
Nat.rec.{u} :
  (C : Nat → Type u) →
  C Nat.zero →
  ((n : Nat) → C n → C (Nat.succ n)) →
  (n : Nat) → C n
```

The recursor's $iota$-rule fires when its principal argument is a constructor. To check `Eq.refl.{0} Nat 6 : Nat.add 2 4 = 6`, the elaborator reduces `Nat.add 2 4` to `6`: $delta$ unfolds `Nat.add`, then $iota$ fires four times through `Nat.rec` as the second argument is decremented to zero.

The full grammar, judgement forms, and typing rules are in @sec:calculus.
