#import "common.typ": *

== Our dependent type theory <sec:type-theory>

qdt's input language is a small dependent type theory. This section fixes its syntax and reduction rules.

A dependent type may carry values: `Vector α n` records the length as the value `n : Nat`, and `Vector α (succ n)` is therefore non-empty by typing. Once types carry values, type equality requires evaluation: `Vector α (2 + 3)` and `Vector α 5` agree only once `2 + 3` reduces to `5`. The elaborator's _conversion checker_ decides this _definitional_ equality, the smallest congruence under the calculus's reduction rules. Propositional equality `Eq A x y`, witnessed by `Eq.refl x : Eq A x x`, is a separate type the programmer reasons about explicitly.

=== Grammar <sec:fragment>

The calculus uses universes _à la Tarski_ @martinlof1984#footnote[The popular _Russell_-style alternative collapses terms and types into one. The Tarski choice gives cleaner categorical semantics.]. The grammar is:

#align(center, table(
  columns: (auto, auto, auto),
  align: (right + horizon, left + horizon, right + horizon),
  stroke: none,
  column-gutter: (0.4em, 2em),
  $ell ::=$, $n | 0 | sans("succ")(ell) | max(ell, ell)$, [(universe levels)],
  $A, B ::=$, $sans("Type")_ell$, [(universe)],
  $|$, $Pi_(x : A) B$, [(dependent function type)],
  $|$, $sans("El")(t)$, [(decoding a type code)],
  $t, s ::=$, $x_i | c.{overline(ell)}$, [(variable, constant)],
  $|$, $lambda (x : A). t | t thin s$, [(function abstraction, application)],
  $|$, $t.k$, [(field projection)],
  $|$, $sans("let") thin x : A := t thin sans("in") thin s$, [(let-binding)],
  $|$, $sans("Type'")_ell | Pi'_(x : t) s$, [(universe and function type codes)],
))

Variables $x_i$ are de Bruijn indices, where $i$ refers to the $i$-th enclosing binder counted from the use site. Global constants $c.{overline(ell)}$ are applied to universe arguments at each use site, and $t.k$ projects the $k$-th field. The primed term formers $sans("Type'")_ell$ and $Pi'_(x : t) s$ are term-level _codes_ for the corresponding type formers; the type-level constructor $sans("El")(t)$ decodes a code into a type. Inductive declarations introduce a new type former, its constructors, and a recursor.

=== Universes

Types are stratified into a hierarchy

$ sans("Type")_0 thin : thin sans("Type")_1 thin : thin sans("Type")_2 thin : thin dots $

with $sans("Type")_u : sans("Type")_(u+1)$ for each $u$. The hierarchy is _non-cumulative_: each $sans("Type")_u$ inhabits exactly one universe, $sans("Type")_(u+1)$.

A definition can be parameterised by universe levels:

```lean
def id.{u} (α : Type u) (x : α) : α := x
```

Levels are a separate sort of variable from term-level binders and must be instantiated explicitly at each use site (`id.{0}`, `id.{u + 1}`). There is no universe-level inference: the programmer writes every level argument#footnote[Inference would require a constraint solver over a join-semilattice, which is out of scope of this thesis.].

=== Inductive types

An inductive type @dybjer1994inductive is introduced by its constructors. `Nat` is built from `Nat.zero` and `Nat.succ`. The declaration adds a _recursor_ for structural elimination:

```lean
Nat.rec.{u} :
  (C : Nat → Type u) →
  C Nat.zero →
  ((n : Nat) → C n → C (Nat.succ n)) →
  (n : Nat) → C n
```

The recursor takes a motive `C` and one branch per constructor. qdt has no primitive pattern matching, so case analysis is written through recursors.

=== Reduction and conversion

Definitional equality is generated by five computation rules, named by Greek letters in the type-theory literature:

- $beta$-_reduction_: $(lambda x. b) thin a equiv b[a slash x]$, function application.
- $delta$-_reduction_: $c equiv t$ when the global environment binds the constant $c$ to body $t$, definition unfolding.
- $zeta$-_reduction_: $sans("let") thin x := a thin sans("in") thin b equiv b[a slash x]$, let inlining.
- $eta$-_reduction_: at a function type, $f equiv lambda x. f thin x$, so a function equals its expansion whether or not it is syntactically a lambda. At a single-constructor inductive (a structure or record such as $Sigma$), $s equiv c(s.1, dots, s.k)$, so a structure equals the constructor applied to its projections.
- $iota$-_reduction_: a recursor applied to a constructor reduces to the corresponding branch. For `Nat`, $sans("Nat.rec") thin C thin z thin s thin (sans("succ") thin n) ~> s thin n thin (sans("Nat.rec") thin C thin z thin s thin n)$ and $sans("Nat.rec") thin C thin z thin s thin sans("zero") ~> z$.

As a worked example, the elaborator checks `Eq.refl.{0} Nat 6 : Nat.add 2 4 = 6` by reducing the left-hand side. $delta$ unfolds `Nat.add` to the recursor. Then $iota$ fires as the recursion's principal argument is unwound from `4` through `succ`s down to `0`, and the term reduces to `succ (succ (succ (succ 2)))`, which is `6`.

Of the five rules, only $delta$ crosses declaration boundaries: applying it looks up another constant in the global environment. The other four operate on a term's own structure. A conversion check that fires $delta$ on `foo` depends on `foo`'s body; one that does not is independent of any change to `foo`. The build system tracks these dynamic cross-declaration dependencies (@sec:verifying-the-cache).

