#import "@preview/curryst:0.5.1": prooftree, rule

== Core calculus <sec:calculus>

The elaborator targets a dependent type theory in the tradition of Martin-Löf @martinlof1984, with Tarski-style universes @dybjer1996internal. The grammar is:

$
  ell &::= n | 0 | sans("succ")(ell) | max(ell, ell) & quad "(universe levels)" \
  A, B &::= sans("Type")_ell | Pi (x : A). B | sans("El")(t) & quad "(types)" \
  t, s &::= sans("Type'")_ell | x_i | c.{overline(ell)} | lambda (x : A). t | t thin s | Pi' (x : t). s | t.k | sans("let") thin x : A := t thin sans("in") thin s & quad "(terms)"
$

Variables $x_i$ are de Bruijn indices, $c.{overline(ell)}$ are global constants applied to universe arguments, and $t.k$ projects the $k$-th field. The primed term formers $sans("Type'")_ell$ and $Pi' (x : t). s$ are the term-level codes for the corresponding type formers; $sans("El")$ decodes a term-level code into a type.

=== Judgement forms

The theory has six judgement forms over a global environment $Delta$ and a local context $Gamma$:

$
  & tack.r Delta thin sans("sig")                   & quad & "global environment well-formedness" \
  & Delta; Gamma tack.r                             & quad & "context well-formedness" \
  & Delta; Gamma tack.r A thin sans("type")         & quad & "type well-formedness" \
  & Delta; Gamma tack.r t : A                       & quad & "term typing" \
  & Delta; Gamma tack.r A equiv B thin sans("type") & quad & "type equality" \
  & Delta; Gamma tack.r a equiv b : A               & quad & "term equality"
$

=== Typing rules

Introduction and elimination of dependent functions, and the conversion rule:

#align(center, stack(
  dir: ltr,
  spacing: 2em,
  prooftree(rule(
    name: $Pi sans("-I")$,
    $Delta; Gamma tack.r lambda (x : A). b : Pi (x : A). B$,
    $Delta; Gamma tack.r A thin sans("type")$,
    $Delta; Gamma, x : A tack.r b : B$,
  )),
  prooftree(rule(
    name: $Pi sans("-E")$,
    $Delta; Gamma tack.r f thin a : B[a\/x]$,
    $Delta; Gamma tack.r f : Pi (x : A). B$,
    $Delta; Gamma tack.r a : A$,
  )),
  prooftree(rule(
    name: $sans("Conv")$,
    $Delta; Gamma tack.r t : B$,
    $Delta; Gamma tack.r t : A$,
    $Delta; Gamma tack.r A equiv B thin sans("type")$,
  )),
))

Variables and constants are typed by context and environment lookup; let-bindings check the bound value and then the body in the extended context. The Conv rule is what makes type checking nontrivial: deciding $A equiv B$ requires reducing terms, which is the subject of @sec:nbe and @sec:conv.

=== Definitional equality

Definitional equality is the least congruence generated by:

- $beta$: $quad (lambda (x : A). b) thin a equiv b[a\/x]$
- $delta$: $quad c.{overline(ell)} equiv t quad$ when $Delta(c) = t$
- $zeta$: $quad sans("let") thin x : A := a thin sans("in") thin b equiv b[a\/x]$
- $eta$: $quad f equiv lambda (x : A). f thin x quad$ at function type
- $iota$: recursor applied to a constructor computes to the corresponding branch

=== Inductive types

An inductive declaration introduces a type, its constructors, and a recursor. For `Vector`, a length-indexed list:

```lean
inductive Vector.{u} (α : Type u) : Nat → Type u where
  | nil : Vector α Nat.zero
  | cons (n : Nat) (head : α) (tail : Vector α n) : Vector α (Nat.succ n)
```

This generates the type, constructors, and a recursor `Vector.rec.{v, u}` that eliminates a `Vector` by providing a case for `nil` and a case for `cons`:

```lean
Vector.rec.{v, u} :
  (α : Type u) →
  (C : (n : Nat) → Vector α n → Type v) →
  C Nat.zero (Vector.nil α) →
  ((n : Nat) → (head : α) → (tail : Vector α n) → C n tail → C (Nat.succ n) (Vector.cons α n head tail)) →
  (n : Nat) → (xs : Vector α n) → C n xs
```

There is no primitive pattern matching: all computation on inductives proceeds through the recursor, and $iota$-reduction fires when the recursor is applied to a constructor. Structures (single-constructor inductives) additionally support projections $t.k$ extracting the $k$-th field.
