=== Conversion checking <sec:conv>

Conversion is the hot loop of a dependent type checker. Every typing rule that crosses a definitional equality calls it, and most of those calls compare terms whose heads already agree. Forcing both sides to normal form just to discover this is wasteful. Kovács's smalltt @kovacs2023smalltt structures conversion as a three-mode gamble that pays only for the unfoldings it actually needs.

The default mode is *rigid*. When two glued values present the same defined head, rigid bets the spines will agree without forcing either body, and hands control to *flex*. Flex walks the spines and unfolds nothing; the first mismatch fails immediately, and rigid then enters *full*, where every definition is unfolded on encounter. Once full takes over a subterm it stays in full for that subterm's recursion. There is at most one backtrack: the cheap flex pass either succeeds and saves the unfolding cost, or fails after walking only as much of the spines as matched.

Watching this on `Nat.add 2 3` against itself: both sides are glued at `Nat.add`, so rigid passes to flex. Flex walks the spines structurally --- `succ (succ zero)` against the same for the first argument, then `succ (succ (succ zero))` against the same for the second --- and reports agreement. `Nat.add`'s body is never fetched; no dependency on it is recorded.

Compare `Nat.add 2 3` against `5`. The heads differ --- a glued definition on one side, a `Nat.succ` neutral on the other --- so flex cannot apply. Full takes over, forces the left through `whnf`, which $delta$-unfolds `Nat.add` and fires the recursor's $iota$-rule three times to land on `succ (succ (succ (succ (succ zero))))`, which is `5`. The check succeeds, but `Nat.add`'s body was read, so the build framework records the dependency.

The checker also handles the two $eta$ rules of @sec:type-theory. Function $eta$ fires when one side of a comparison is a $lambda$ and the other is any term: both sides are applied to a fresh variable at the current de Bruijn level and their bodies are compared, so $f$ is treated as a $lambda$ even when it is not syntactically one. Structure $eta$ fires when one side is a constructor application of a single-constructor inductive: each of the other side's projections is compared against the matching field, so $s$ and $sans("mk")(s.1, dots, s.k)$ are equated without forcing $s$ into constructor form.

